project:
  type: book

book:
  title: "Knowledge"
  subtitle: "A Human Interest Story"
  author: "Brian Weatherson"
  date: now
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - history.qmd
    - interests.qmd
    - beliefs.qmd
    - knowledge.qmd
    - inquiry.qmd
    - ties.qmd
    - changes.qmd
    - rationality.qmd
    - evidence.qmd
    - power.qmd
    - references.qmd
  sidebar:
    search: true
    collapse-level: 3
    title: "Knowledge: <br>A Human Interest Story"

bibliography: references.bib

format:
  html:
    theme: 
      light: 
        - solar
        - html-fonts.scss
        - solar-defaults.scss
      dark:
        - solar
        - html-fonts.scss
    linestretch: 1.7
    toc: true
    toc-depth: 3
    reference-location: margin
    margin-header: "&nbsp;"
    fontsize: 1.2em
    include-in-header:
      - text: |
          <style>
          @import url('https://fonts.googleapis.com/css2?family=Alegreya&family=Alegreya+Sans:wght@500&display=swap');
          </style>
    mainfont: "Alegreya"
  pdf:
    documentclass: scrbook
    geometry: "left=1.95in,right=1.95in,top=1.78in,bottom=1.78in"
    mainfont: STIX Two Math
    sansfont: Lato
    mainfontoptions: BoldFont = STIX Two Text SemiBold, ItalicFont = STIX Two Text Italic, Scale = MatchLowercase
    biblio-style: philreview
    include-in-header: 
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \renewcommand{\chaptermark}[1]{\markboth{#1 }{}}
        \renewcommand{\sectionmark}[1]{\markright{\thesection\ #1}}
        \fancyhf{}
        \fancyhead[CE]{\nouppercase{\textit \leftmark}}
        \fancyhead[CO]{\nouppercase{\textit \rightmark}}
        \fancyhead[LE,RO]{\thepage}
        \fancyfoot{}
        \renewcommand{\headrulewidth}{0pt}
        \setlength\heavyrulewidth{0ex}
        \setlength\lightrulewidth{0ex}
        \addtolength{\headheight}{1.6pt}
  docx:
    toc: true
    number-sections: true
  epub:
    toc: true
    number-sections: true

editor: visual


