project:
  type: book

book:
  title: "Knowledge"
  subtitle: "A Human Interest Story"
  author: "Brian Weatherson"
  date: now
  downloads: [pdf, epub, docx]
  repo-url: https://github.com/bweatherson/kahis-quarto
  repo-actions:
    - issue
  chapters:
    - index.qmd
    - overture.qmd
    - interests.qmd
    - beliefs.qmd
    - knowledge.qmd
    - inquiry.qmd
    - ties.qmd
    - changes.qmd
    - rationality.qmd
    - evidence.qmd
    - power.qmd
    - references.qmd
  sidebar:
    search: true
    collapse-level: 3
    title: "Knowledge: <br>A Human Interest Story"

bibliography: references.bib
csl: ergo.csl

comments:
  hypothesis: 
    theme: clean

format:
  html:
    theme: 
      light: 
        - solar
        - html-fonts.scss
        - solar-defaults.scss
      dark:
        - solar
        - html-fonts.scss
        - dark-table.scss
    linestretch: 1.6
    toc: true
    toc-title: "In this chapter:"
    toc-depth: 3
    toc-location: right
    reference-location: margin
    margin-header: "&nbsp;"
    fontsize: 1.2em
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://use.typekit.net/uzz2drx.css">
    mainfont: "ff-scala-sans-pro, sans-serif"
    html-math-method: mathjax
    self-contained: false
  pdf:
    documentclass: scrbook
    keep-tex: true
    geometry: "left=2in,right=2in,top=1.78in,bottom=1.78in"
    mathspec: false
    mathfont: Garamond-Math
    mainfont: EB Garamond Math
    sansfont: Europa-Bold
    mainfontoptions: 
      - ItalicFont=EB Garamond Italic
      - BoldFont=EB Garamond Bold
    biblio-style: philreview
    fontsize: 12pt
    linkcolor: black
    citecolor: black
    urlcolor: black
    link-citations: true
    include-in-header: 
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \renewcommand{\chaptermark}[1]{\markboth{#1 }{}}
        \renewcommand{\sectionmark}[1]{\markright{\thesection\ #1}}
        \fancyhf{}
        \fancyhead[CE]{\nouppercase{\textit \leftmark}}
        \fancyhead[CO]{\nouppercase{\textit \rightmark}}
        \fancyhead[LE,RO]{\thepage}
        \fancyfoot{}
        \renewcommand{\headrulewidth}{0pt}
        \setlength\heavyrulewidth{0ex}
        \setlength\lightrulewidth{0ex}
        \addtolength{\headheight}{1.6pt}
  docx:
    toc: true
    reference-doc: my-template.docx
    output-file: "Knowledge"
    number-sections: true
  epub:
    toc: true
    number-sections: true

editor: visual

