<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Evidence – Knowledge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./power.html" rel="next">
<link href="./rationality.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean"
}
</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<link rel="stylesheet" href="https://use.typekit.net/uzz2drx.css">


</head>

<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Brian Weatherson</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-papers" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Papers</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-papers">    
        <li>
    <a class="dropdown-item" href="https://brian.weatherson.org/quarto/papers.html">
 <span class="dropdown-text">All Papers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://brian.weatherson.org/quarto/epist.html">
 <span class="dropdown-text">Epistemology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://brian.weatherson.org/quarto/gdt.html">
 <span class="dropdown-text">Games and Decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://brian.weatherson.org/quarto/books.html">
 <span class="dropdown-text">On Books</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-books" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Books</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-books">    
        <li>
    <a class="dropdown-item" href="https://brian.weatherson.org/ne/">
 <span class="dropdown-text">Normative Externalism</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://lda.weatherson.org/">
 <span class="dropdown-text">A History of Philosophy Journals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://brian.weatherson.org/kahis/">
 <span class="dropdown-text">Knowledge: A Human Interest Story</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://brian.weatherson.org/quarto/cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://brian.weatherson.org/quarto/teaching.html"> 
<span class="menu-text">Teaching Notes</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/bweatherson/kahis-quarto" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Knowledge.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Knowledge.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Knowledge.docx">
              <i class="bi bi-file-word pe-1"></i>
            Download Docx
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./evidence.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Evidence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./beliefs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Belief</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./knowledge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Knowledge</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inquiry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inquiry</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Ties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Changes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rationality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Rationality</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evidence.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Evidence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Power</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p>&nbsp;</p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">In this chapter:</h2>
   
  <ul>
  <li><a href="#sec-evpuzzle" id="toc-sec-evpuzzle" class="nav-link active" data-scroll-target="#sec-evpuzzle"><span class="header-section-number">9.1</span> A Puzzle About Evidence</a></li>
  <li><a href="#sec-simplesolution" id="toc-sec-simplesolution" class="nav-link" data-scroll-target="#sec-simplesolution"><span class="header-section-number">9.2</span> A Simple, but Incomplete, Solution</a></li>
  <li><a href="#sec-radicalinterpretation" id="toc-sec-radicalinterpretation" class="nav-link" data-scroll-target="#sec-radicalinterpretation"><span class="header-section-number">9.3</span> The Radical Interpreter</a></li>
  <li><a href="#sec-globalgame" id="toc-sec-globalgame" class="nav-link" data-scroll-target="#sec-globalgame"><span class="header-section-number">9.4</span> Risk-Dominant Equilibria</a>
  <ul class="collapse">
  <li><a href="#sec-cvdproof" id="toc-sec-cvdproof" class="nav-link" data-scroll-target="#sec-cvdproof"><span class="header-section-number">9.4.1</span> The Dominance Argument for Risk-Dominant Equilibria</a></li>
  <li><a href="#sec-perfectri" id="toc-sec-perfectri" class="nav-link" data-scroll-target="#sec-perfectri"><span class="header-section-number">9.4.2</span> Making One Signal Precise</a></li>
  </ul></li>
  <li><a href="#sec-evsolution" id="toc-sec-evsolution" class="nav-link" data-scroll-target="#sec-evsolution"><span class="header-section-number">9.5</span> Objections and Replies</a></li>
  <li><a href="#sec-cutelim" id="toc-sec-cutelim" class="nav-link" data-scroll-target="#sec-cutelim"><span class="header-section-number">9.6</span> Evidence, Knowledge and Cut-Elimination</a></li>
  <li><a href="#sec-basic" id="toc-sec-basic" class="nav-link" data-scroll-target="#sec-basic"><span class="header-section-number">9.7</span> Basic Knowledge and Non-Inferential Knowledge</a></li>
  <li><a href="#sec-neta" id="toc-sec-neta" class="nav-link" data-scroll-target="#sec-neta"><span class="header-section-number">9.8</span> Holism and Defeaters</a></li>
  <li><a href="#sec-weakness" id="toc-sec-weakness" class="nav-link" data-scroll-target="#sec-weakness"><span class="header-section-number">9.9</span> Epistemic Weakness</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/bweatherson/kahis-quarto/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-evidence" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Evidence</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-evpuzzle" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-evpuzzle"><span class="header-section-number">9.1</span> A Puzzle About Evidence</h2>
<p>In <a href="interests.html#sec-orthodoxevidence" class="quarto-xref"><span>Section 2.3.4</span></a>, I argued that evidence can be interest-relative. The key example involved someone I called Parveen. Recall that she’s in a restaurant and notices an old friend, Rahul, across the restaurant. The conditions for detecting people aren’t perfect, and she’s surprised Rahul is here. Still, we’d ordinarily say it is part of her evidence that Rahul is in this restaurant. She doesn’t infer this from other facts, and she would not be called on to defend it if she relies on it in ordinary circumstances. She then plays the Red-Blue game, with these sentences.</p>
<ul>
<li>The red sentence is <em>Two plus two equals four</em>.</li>
<li>The blue sentence is <em>Rahul is in this restaurant</em>.</li>
</ul>
<p>The key premises for the argument that evidence is interest-relative are:</p>
<ul>
<li>The unique rational play for Parveen is Red-True; and</li>
<li>If evidence is interest-invariant, it is rational for Parveen to play Blue-True.</li>
</ul>
<p>That argument shows that evidence is interest-relative. But it raises, without answering, two big questions:</p>
<ol type="1">
<li>When do interests matter for evidence?</li>
<li>When do interests matter for knowledge?</li>
</ol>
<p>I used to think that there was an easy answer to the second question. A change in interest causes one to lose knowledge that <em>p</em> iff one becomes interested in a question which, given one’s evidence, is rationally answered differently depending on whether or not one answers the question conditional on <em>p</em>. This answer is true as far as it goes, but it isn’t particularly explanatory unless one holds fixed the evidence between the earlier and later set of interests. And that is just what I said should not be held fixed.</p>
<p>The aim of this chapter is to answer both questions simultaneously.</p>
</section>
<section id="sec-simplesolution" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sec-simplesolution"><span class="header-section-number">9.2</span> A Simple, but Incomplete, Solution</h2>
<p>To keep things relatively simple, I’ll assume in this chapter that Parveen is an expected utility maximiser. More carefully, I’ll assume that the reasons covered in <a href="ties.html" class="quarto-xref"><span>Chapter 6</span></a> about why expected utility theory is only an approximation to the correct theory of rational choice are not relevant. From here on, we’ll assume we’re in a situation where expected utility theory is close enough to the true theory of rational choice.</p>
<p>At a very high level of abstraction, we can think about the problem facing Parveen (or anyone else whose evidence might be interest-sensitive), as follows. They have some option <em>o</em>, and given their interests it matters whether the expected value of <em>o</em> is above or below <em>x</em>. I’ll write <em>v</em>(•) for the function from options to their expected value, so the question here is whether or not <em>v</em>(<em>o</em>) us at least <em>x</em>.</p>
<p>There is some background <em>K</em> that is uncontroversially in Parveen’s evidence. There is some further proposition <em>p</em> which might or might not be in her evidence; that’s what the change of interests calls into question. It is uncontroversial that her evidence includes some background <em>K</em>, and controversial whether it includes some contested proposition <em>p</em>. For any <em>q</em> in <em>K</em>,&nbsp;<em>v</em>(<em>o</em>&nbsp;|&nbsp;<em>q</em>)&nbsp;=&nbsp;<em>v</em>(<em>o</em>). That is, expected values are conditional on evidence.</p>
<p>A common idealisation helps capture this last idea. Assume there is a prior value function <em>v</em><sup>-</sup>, with a similar metaphysical status to the prior probability function. Then for any choice <em>c</em>,&nbsp;<em>v</em>(<em>c</em>)&nbsp;=&nbsp;<em>v</em><sup>-</sup>(<em>c</em>&nbsp;|&nbsp;<em>E</em>), where <em>E</em> is the evidence Parveen has.</p>
<p>Now I can offer a simple, but incomplete, solution to question 2, assuming <em>p</em> is the only proposition whose status as evidence is put into question by the interests-shift, and the only shift in interests is that the question of whether <em>v</em>(<em>o</em>) ≥ <em>x</em> is now relevant. Then she knows <em>p</em> only if [<em>v</em><sup>-</sup>(<em>o</em>|<em>K</em>)&nbsp;+&nbsp;<em>v</em><sup>-</sup>(<em>o</em>|<em>K</em>&nbsp;∧&nbsp;<em>p</em>)]/2&nbsp;≥&nbsp;<em>x</em>. That is, if <em>p</em>’s status as evidence is questionable, the relevant ‘value’ for <em>o</em> is the average of its expected value with and without <em>p</em> being evidence.</p>
<p>That gets the right answer about what Parveen should do. Her evidence may or may not include that Rahul is in the restaurant. If it does, then Blue-True has a value of $50. If it does not, then Blue-True’s value is somewhat lower. Even if the evidence includes that someone who looks a lot like Rahul is in the restaurant, the value of Blue-True might only be $45. Averaging them out, the value is less than $50. It would only be rational to play Blue-True if was worth $50. So she shouldn’t play Blue-True.</p>
<p>Great! Well, great except for two monumental problems. The first is that it only handles this very special case. The second is that the formula used, take the arithmetic mean of the values with and without the evidence, is barely better than arbitrary. It gets one thing right, it says Parveen shouldn’t play Blue-True, but it’s hardly alone in having that virtue.</p>
<p>Pragmatic encroachment starts with a very elegant, very intuitive, principle: you only know the things you can reasonably take to be settled for the purposes of current deliberation. This arbitrary averaging formula is not elegant or intuitive.</p>
<p>Happily, the two problems have a common solution. Setting it out requires going over recent work on coordination games.</p>
</section>
<section id="sec-radicalinterpretation" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-radicalinterpretation"><span class="header-section-number">9.3</span> The Radical Interpreter</h2>
<p>William <span class="citation" data-cites="Harper1986">Harper (<a href="references.html#ref-Harper1986" role="doc-biblioref">1986</a>)</span> pointed out that many decision problems are really better thought of as games. For instance, Newcomb’s Problem can be represented by the game in <a href="#tbl-Newcomb" class="quarto-xref">Table&nbsp;<span>9.1</span></a>, with the human as Row and the demon as Column.</p>
<div id="tbl-Newcomb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Newcomb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Newcomb’s Problem as a game.
</figcaption>
<div aria-describedby="tbl-Newcomb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;">Predict 1 Box</td>
<td style="text-align: center;">Predict 2 Boxes</td>
</tr>
<tr class="even">
<td style="text-align: right;">Choose 1 Box</td>
<td style="text-align: center;">1000, 1</td>
<td style="text-align: center;">0, 0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Choose 2 Boxes</td>
<td style="text-align: center;">1001, 0</td>
<td style="text-align: center;">1, 1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>There is a unique equilibrium of this game: the bottom right corner. The reason it’s the unique equilibrium is similar to the reason that two-boxers say to take two boxes: no other option is ratifiable for both players.</p>
<p>This section will be centered around a game that is only slightly more complicated. I call it The Interpretation Game. The game has two players. As in Newcomb’s Problem, they are a human and a mythical creature. Here the mythical creature is The Radical Interpreter.</p>
<p>In any game, the payouts are a function of what will happen to the players in each situation, and the players’ values over those outcomes. To turn a physical situation into a game, we need to know the players’ goals. Here are the goals I’ll assume our players have:</p>
<ul>
<li>The Radical Interpreter assigns mental states to Human with the aim of making the action Human actually chooses the rational choice. I assume here that the ‘mental states’ include Human’s evidence. Indeed, the main thing I’ll have The Radical Interpreter do is assign evidence to Human.</li>
<li>Human aims to maximise expected utility given their evidence. That last phrase, ‘their evidence’, should be read de re. More precisely, they aim to do the thing that is expected utility maximising given the evidence they actually have. (So their own views about their evidence don’t matter; all that matters is what their evidence really is.)</li>
</ul>
<p>Given these aims, The Radical Interpreter and Human often play coordination games. They will both achieve their aims if they act the ‘same’ way. That is, when it is uncertain whether <em>p</em> is part of Human’s evidence, the coordination outcomes are:</p>
<ul>
<li>The Radical Interpreter says that <em>p</em> is part of Human’s evidence, and Human maximises expected utility given <em>K</em> ∧&nbsp;<em>p</em>.</li>
<li>The Radical Interpreter says that <em>p</em> is part of Human’s evidence, and Human maximises expected utility given <em>K</em>.</li>
</ul>
<p>Coordination games typically have multiple equilibria, and that will also be the case here.</p>
<p>Let’s focus on one example. Human is offered a bet on <em>p</em>. If the bet wins, it wins 1 util; if the bet loses, it loses 100 utils. Human’s only choice is to Take or Decline the bet. The proposition <em>p</em>, the subject of the bet, is like the claim that Rahul is in the restaurant. That is, it is unclear whether it is in Human’s evidence. Again, let <em>K</em> be the rest of Human’s evidence, and stipulate that Pr(<em>p</em> |<em>K</em>)&nbsp;=&nbsp;0.9. Each party now faces a choice.</p>
<ul>
<li>The Radical Interpreter has to choose whether <em>p</em> is part of Human’s evidence or not.</li>
<li>Human has to decide whether to Take or Decline the bet.</li>
</ul>
<p>The payouts for the game are given in <a href="#tbl-radical-interpreter" class="quarto-xref">Table&nbsp;<span>9.2</span></a>.</p>
<div id="tbl-radical-interpreter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-radical-interpreter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.2: The Radical Interpreter game.
</figcaption>
<div aria-describedby="tbl-radical-interpreter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;"><em>p</em>&nbsp;∈&nbsp;<em>E</em></td>
<td style="text-align: center;"><em>p</em>&nbsp;∉&nbsp;<em>E</em></td>
</tr>
<tr class="even">
<td style="text-align: right;">Take the Bet</td>
<td style="text-align: center;">1, 1</td>
<td style="text-align: center;">-9.1, 0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Decline the Bet</td>
<td style="text-align: center;">0, 0</td>
<td style="text-align: center;">0, 1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Why is this the right table? Let’s start with The Radical Interpreter.</p>
<p>The Radical Interpreter achieves their aim iff the following biconditional obtains: Human takes the bet iff <em>p</em> is part of their evidence. That’s why they get payout 1 in the cells where that obtains, and 0 otherwise.</p>
<p>Most of Human’s payouts are obvious. In the bottom row, they are guaranteed 0, since the bet is declined. In the top left, the bet wins with probability 1, so their expected return is 1. In the top right, the bet wins with probability 0.9, so the expected return of taking it is 1&nbsp;×&nbsp;0.9&nbsp;-&nbsp;100&nbsp;×&nbsp;0.1&nbsp;=&nbsp;-9.1.</p>
<p>There are two Nash equilibria for the game - the top left and the bottom right. We could stop here and say that according to IRT it is indeterminate whether <em>p</em> is part of Human’s evidence. But we can do better.</p>
<p>But to do that, I need to survey more contested areas of game theory. In particular, I need to introduce some work on equilibrium choice. To do that, it helps to think about a game that is inspired by an example of Rousseau’s.</p>
</section>
<section id="sec-globalgame" class="level2 page-columns page-full" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sec-globalgame"><span class="header-section-number">9.4</span> Risk-Dominant Equilibria</h2>
<p><a href="#tbl-generic-game" class="quarto-xref">Table&nbsp;<span>9.3</span></a> is the abstract version of a two-player, two-option game.</p>
<div id="tbl-generic-game" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-generic-game-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.3: A generic 2 by 2 by 2 game.
</figcaption>
<div aria-describedby="tbl-generic-game-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;"><em>a</em></td>
<td style="text-align: center;"><em>b</em></td>
</tr>
<tr class="even">
<td style="text-align: right;"><em>A</em></td>
<td style="text-align: center;"><em>r</em><sub>11</sub>,&nbsp;<em>c</em><sub>11</sub></td>
<td style="text-align: center;"><em>r</em><sub>12</sub>,&nbsp;<em>c</em><sub>12</sub></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><em>B</em></td>
<td style="text-align: center;"><em>r</em><sub>21</sub>,&nbsp;<em>c</em><sub>21</sub></td>
<td style="text-align: center;"><em>r</em><sub>22</sub>,&nbsp;<em>c</em><sub>22</sub></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>What are usually called Stag Hunt games have the following eight characteristics.</p>
<ol type="1">
<li><em>r</em><sub>11</sub>&nbsp;&gt;&nbsp;<em>r</em><sub>21</sub></li>
<li><em>r</em><sub>22</sub>&nbsp;&gt;&nbsp;<em>r</em><sub>12</sub></li>
<li><em>c</em><sub>11</sub>&nbsp;&gt;&nbsp;<em>c</em><sub>12</sub></li>
<li><em>c</em><sub>22</sub>&nbsp;&gt;&nbsp;<em>c</em><sub>21</sub></li>
<li><em>r</em><sub>11</sub>&nbsp;&gt;&nbsp;<em>r</em><sub>22</sub></li>
<li><em>c</em><sub>11</sub>&nbsp;≥&nbsp;<em>c</em><sub>22</sub></li>
<li><em>r</em><sub>21</sub>&nbsp;+&nbsp;<em>r</em><sub>22</sub>&nbsp;&gt;&nbsp;<em>r</em><sub>11</sub>&nbsp;+&nbsp;<em>r</em><sub>12</sub></li>
<li><em>c</em><sub>12</sub>&nbsp;+&nbsp;<em>c</em><sub>22</sub>&nbsp;≥&nbsp;<em>c</em><sub>11</sub>&nbsp;+&nbsp;<em>c</em><sub>21</sub></li>
</ol>
<p>The first four conditions say that the game has two (strict) Nash equilibria: <em>Aa</em> and <em>Bb</em>. The next two conditions say that the <em>Aa</em> equilibria is <em>Pareto-optimal</em>: neither player prefers <em>Aa</em> to <em>Bb</em>. In fact it says something a bit stronger: one of the players strictly prefers the <em>Aa</em> equilibria, and the other player does not prefer <em>Bb</em>. The last two conditions say that the <em>Bb</em> equilibria is <em>risk-optimal</em>.</p>
<p>Hans Carlsson and Eric van Damme <span class="citation" data-cites="CarlssonVanDamme1993">(<a href="references.html#ref-CarlssonVanDamme1993" role="doc-biblioref">1993</a>)</span> offer an argument that in any such game, rational players will end up at <em>Bb</em>. The game that Human and The Radical Interpreter are playing fits these eight conditions, and The Radical Interpreter is perfectly rational. So if Carlsson and van Damme are right, The Radical Interpreter will say that <em>p</em>&nbsp;∉&nbsp;<em>E</em>. Indeed, if Carlsson and van Damme are right, the toy theory I offered <a href="#sec-simplesolution" class="quarto-xref"><span>Section 9.2</span></a> will be correct in all cases where it applies.</p>
<p>The rest of this chapter would be much simpler if I thought Carlsson and van Damme’s argument worked in full generality. Unfortunately, I don’t think it does. In particular, I think it fails in the important case where it is common knowledge that both players are rational, and both players know precisely the values of each of the eight payoffs. But I think it does work in the special case where one player has imperfect access to what the payouts are. And that, it turns out, is the special case that matters to us. That’s getting ahead of the story though; let’s start with their argument.</p>
<p>I said games satisfying these conditions are called Stag Hunt games. The name comes from a thought experiment in Rousseau’s <em>Discourse on Inequality</em>.</p>
<blockquote class="blockquote">
<p>They were perfect strangers to foresight, and were so far from troubling themselves about the distant future, that they hardly thought of the morrow. If a deer was to be taken, every one saw that, in order to succeed, he must abide faithfully by his post: but if a hare happened to come within the reach of any one of them, it is not to be doubted that he pursued it without scruple, and, having seized his prey, cared very little, if by so doing he caused his companions to miss theirs. &nbsp;<span class="citation" data-cites="Rousseau1913">(<a href="references.html#ref-Rousseau1913" role="doc-biblioref">Rousseau, 1913: 209–10</a>)</span></p>
</blockquote>
<p>Brian <span class="citation" data-cites="Skyrms2001">Skyrms (<a href="references.html#ref-Skyrms2001" role="doc-biblioref">2001</a>)</span> has argued that these Stag Hunt games are important across philosophy; they are good models for many real-life situations that are often (incorrectly) modeled as Prisoners’ Dilemmas. But going over why that is would be a needless digression. Our focus is on Carlsson and van Damme’s argument that Rousseau was right: a ‘stranger to foresight’, who is just focussing on this game, should take the rabbit.</p>
<p>To make matters a little easier, we’ll focus on a very particular instance of Stag Hunt, the one in <a href="#tbl-stag-hunt" class="quarto-xref">Table&nbsp;<span>9.4</span></a>.</p>
<div id="tbl-stag-hunt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stag-hunt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.4: A simple version of Stag Hunt.
</figcaption>
<div aria-describedby="tbl-stag-hunt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;"><em>a</em></td>
<td style="text-align: left;"><em>b</em></td>
</tr>
<tr class="even">
<td style="text-align: right;"><em>A</em></td>
<td style="text-align: center;">4, 4</td>
<td style="text-align: left;">0, 3</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><em>B</em></td>
<td style="text-align: center;">3, 0</td>
<td style="text-align: left;">3, 3</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The equilibrium <em>Aa</em> is Pareto-optimal: it is the best outcome for each individual. But it is risky, and Carlsson and van Damme suggest a way to turn that risk into an argument for choosing <em>Bb</em>.</p>
<p>Embed <a href="#tbl-stag-hunt" class="quarto-xref">Table&nbsp;<span>9.4</span></a> game in what they call a <em>global game</em>. Our first version of a global game is that each player knows that they will play <a href="#tbl-global-game" class="quarto-xref">Table&nbsp;<span>9.5</span></a>, with <em>x</em> to be selected at random from a flat distribution over [-1, 5].</p>
<div id="tbl-global-game" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-global-game-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.5: The global game.
</figcaption>
<div aria-describedby="tbl-global-game-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;"><em>a</em></td>
<td style="text-align: center;"><em>b</em></td>
</tr>
<tr class="even">
<td style="text-align: right;"><em>A</em></td>
<td style="text-align: center;">4, 4</td>
<td style="text-align: center;">0,&nbsp;<em>x</em></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><em>B</em></td>
<td style="text-align: center;"><em>x</em>, 0</td>
<td style="text-align: center;"><em>x</em>,&nbsp;<em>x</em></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>There isn’t much to say about <a href="#tbl-global-game" class="quarto-xref">Table&nbsp;<span>9.5</span></a> with this prior knowledge. Let’s give the players a little more knowledge. (And we’ll call the players Row and Column to make it easier to refer to each of them.)</p>
<p>Before they play the game, each player will get a noisy signal about the value of <em>x</em>. There will be signals <em>s<sub>R</sub></em> and <em>s<sub>C</sub></em> chosen (independently) from a flat distribution over [<em>x</em>&nbsp;-&nbsp;0.25,&nbsp;<em>x</em>&nbsp;+&nbsp;0.25], and shown to Row and Column respectively. So each player will know the value of <em>x</em> to within ¼, and know that the other player knows it to within ¼ as well. This is a margin of error model, and in those models there is very little that is common knowledge. That, Carlsson and van Damme argue, makes a huge difference.</p>
<p>They go on to prove that iterated deletion of strictly dominated strategies (almost) removes all but one strategy pair. (I’ll go over the proof of this in the next subsection.) Each player will play <em>A</em>/<em>a</em> if the signal is greater than 2, and <em>B</em>/<em>b</em> otherwise.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Surprisingly, this shows that players should play the risk-optimal strategy even when they know the other strategy is Pareto-optimal. When a player gets a signal in (2, 3.75), then they know that <em>x</em>&nbsp;&lt;&nbsp;4, so <em>Bb</em> is the Pareto-optimal equilibrium. But the logic of the global game suggests the risk-dominant equilibrium is what to play.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;Strictly speaking, we can’t rule out various mixed strategies when the signal is precisely 2, but this makes little difference, since that occurs with probability 0.</p></div></div><p>Carlsson and van Damme go on to show that many of the details of this case don’t matter. Most importantly, it doesn’t matter that the margin of error in the signal was ¼; as long as it is positive the argument goes through.</p>
<p>Now what does this show about the game where players know precisely what the value of <em>x</em> is? Equivalently, what does it show about the game where the margin of error is zero?</p>
<p>Carlsson and van Damme argue that it shows that the risk-dominant choice is the right choice there as well. After all, the game where there is perfect knowledge just is a margin of error game, where the margin of error is 0. In previous work I’d endorsed this argument <span class="citation" data-cites="Weatherson2018-WEAIEA-2">(<a href="references.html#ref-Weatherson2018-WEAIEA-2" role="doc-biblioref">Weatherson, 2018</a>)</span>. I now think this was a mistake. The limit case, where the players know the value of <em>x</em>, is special. But, I’ll argue, this doesn’t actually undermine the argument that in the game between Human and The Radical Interpreter, both parties should choose the risk-dominant equilibria.</p>
<p>If the game between Human and The Radical Interpreter is meant to model a real situation, Human won’t know precisely what the payoffs are. That’s because real Humans don’t know precisely what their evidence is. They only know precisely what their evidence is if both positive and negative introspection hold for evidence, and that’s no more plausible than that positive and negative introspection hold for knowledge. As <span class="citation" data-cites="Humberstone2016">Humberstone (<a href="references.html#ref-Humberstone2016" role="doc-biblioref">2016: 380–402</a>)</span> shows, that’s not particularly plausible, even if one doesn’t accept the arguments in <span class="citation" data-cites="Williamson2000">Williamson (<a href="references.html#ref-Williamson2000" role="doc-biblioref">2000</a>)</span> against positive introspection.</p>
<p>If Human doesn’t know precisely what their evidence is, they don’t know the payoffs in games like <a href="#tbl-global-game" class="quarto-xref">Table&nbsp;<span>9.5</span></a>, because those payoffs are expected values. It turns out that’s enough for the iterated dominance argument that Human should play the risk-dominant equilibrium to go through.</p>
<p>To be sure, The Radical Interpreter, who is just an idealisation, presumably does know the payouts in the different states of the game. It turns out, as I’ll go over in <a href="#sec-perfectri" class="quarto-xref"><span>Section 9.4.2</span></a>, that Carlsson and van Damme’s result only needs that one player is uncertain of the payouts. Given the failure of at least negative introspection (and, I’d say, positive introspection), that’s something we can assume.</p>
<p>If Human should play the risk-dominant strategy in <a href="#tbl-radical-interpreter" class="quarto-xref">Table&nbsp;<span>9.2</span></a>, they should decline the bet. So The Radical Interpreter, who can figure this out, should say that <em>p</em> is not part of their evidence. Since one’s evidence just is what The Radical Interpreter says it is, that means that in <a href="#tbl-radical-interpreter" class="quarto-xref">Table&nbsp;<span>9.2</span></a>, <em>p</em> is not part of Human’s evidence.</p>
<p>Applied to the case of Parveen and Rahul, that means that The Radical Interpreter is best off saying it is no part of Parveen’s evidence that Rahul is in the restaurant. More generally, in the simple cases described in <a href="#sec-simplesolution" class="quarto-xref"><span>Section 9.2</span></a>, The Radical Interpreter should say that <em>p</em> is not part of Human’s evidence just in case the equation used there holds.</p>
<p>The result is an interest-relative theory of evidence that is somewhat well motivated. At least, it can be incorporated into a broader theory of rational action.</p>
<p>This model keeps what was good about the pragmatic encroachment theory developed in the previous chapters, while also allowing that evidence can be interest-relative. It does require a considerably more complex theory of rationality than was previously used. Rather than just model rational agents as utility maximisers, they are modelled as playing playing risk-dominant strategies in coordination games under uncertainty about what the payouts are. Still, it turns out that this is little more than assuming that they maximise evidential expected utility, and they expect others (at least perfectly rational abstract others) to do the same, and they expect those others to expect they will maximise expected utility, and so on.</p>
<p>The rest of this section goes into more technical detail about Carlsson and van Damme’s example. Readers not interested in these details can skip ahead to <a href="#sec-evsolution" class="quarto-xref"><span>Section 9.5</span></a>. In <a href="#sec-cvdproof" class="quarto-xref"><span>Section 9.4.1</span></a> I summarise their argument that we only need iterated deletion of strictly dominated strategies to get the result that rational players will play the risk-dominant strategies. Then in <a href="#sec-perfectri" class="quarto-xref"><span>Section 9.4.2</span></a> I offer a small generalisation of their argument, showing that it still goes through when one of the players gets a precise signal, and the other gets a noisy signal.</p>
<section id="sec-cvdproof" class="level3 page-columns page-full" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="sec-cvdproof"><span class="header-section-number">9.4.1</span> The Dominance Argument for Risk-Dominant Equilibria</h3>
<p>Two players, Row (or R) and Column (or C) will play the game depicted in <a href="#tbl-global-game" class="quarto-xref">Table&nbsp;<span>9.5</span></a>. They won’t be told what <em>x</em> is, but they will get a noisy signal of <em>x</em>, drawn from an even distribution over [<em>x</em>&nbsp;-&nbsp;0.25,&nbsp;<em>x</em>&nbsp;+&nbsp;0.25]. Call these signals <em>s<sub>R</sub></em> and <em>s<sub>C</sub></em>. Each player must then choose <em>A</em>, getting either 4 or 0 depending on the other player’s choice, or choose <em>B</em>, getting <em>x</em> for sure.</p>
<p>Before getting the signal, the players must choose a strategy. In this context, a strategy is a function from signals to choices. Since the higher the signal is, the better it is to play <em>B</em>, we can more or less equate strategies with ‘tipping points’, where the player plays <em>B</em> if the signal is above the tipping point, and <em>A</em> below the tipping point.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;I’m ignoring mixed strategies here, and strategies that differ in cases where the signal is right at the tipping point. It’s trivial but tedious to extend the proof to cover these cases.</p></div></div><p>Call the tipping points for Row and Column respectively <em>T<sub>R</sub></em> and <em>T<sub>C</sub></em>. Since this game is symmetric, we’ll just have to show that in conditions of common knowledge of rationality, <em>T<sub>R</sub></em>&nbsp;=&nbsp;2. It follows by symmetry that <em>T<sub>C</sub></em>&nbsp;=&nbsp;2 as well. The only rule that will be used is iterated deletion of strictly dominated strategies.</p>
<p>The return to a strategy is uncertain, even given the other player’s strategy. But given the strategies of each player, each players’ expected return can be computed. That will be treated as the return to the strategy pair.</p>
<p>Note first that <em>T<sub>R</sub></em>&nbsp;=&nbsp;4.25 strictly dominates any strategy where <em>T<sub>R</sub></em>&nbsp;=&nbsp;<em>y</em>&nbsp;&gt;&nbsp;4.25. If <em>s<sub>R</sub></em>&nbsp;∈&nbsp;(4.25,&nbsp;<em>y</em>), then <em>T<sub>R</sub></em> is guaranteed to return above 4, and the alternative strategy is guaranteed to return 4. In all other cases, the strategies have the same return. There is some chance that <em>s<sub>R</sub></em>&nbsp;∈&nbsp;(4.25,&nbsp;<em>y</em>). So we can delete all strategies <em>T<sub>R</sub></em>&nbsp;=&nbsp;<em>y</em>&nbsp;&gt;&nbsp;4.25, and similarly all strategies <em>T<sub>C</sub></em>&nbsp;=&nbsp;<em>y</em>&nbsp;&gt;&nbsp;4.25. By similar reasoning, we can rule out <em>T<sub>R</sub></em>&nbsp;&lt;&nbsp;-0.25 and <em>T<sub>C</sub></em>&nbsp;&lt;&nbsp;-0.25.</p>
<p>If <em>s<sub>R</sub></em>&nbsp;∈&nbsp;[-0.75,&nbsp;4.75], then it is equally likely that <em>x</em> is above <em>sR</em> as it is below it. Indeed, the posterior distribution of <em>x</em> is flat over [<em>s<sub>R</sub></em>&nbsp;-&nbsp;0.25,&nbsp;<em>s<sub>R</sub></em>&nbsp;+&nbsp;0.25]. From this it follows that the expected return of playing <em>B</em> after seeing signal <em>sR</em> is just <em>sR</em>.</p>
<p>Now comes the important step. For arbitrary <em>y</em>&nbsp;&gt;&nbsp;2, assume we know that <em>T<sub>C</sub></em>&nbsp;≤&nbsp;<em>y</em>. Consider the expected return of playing <em>A</em> given various values for <em>s<sub>R</sub></em>&nbsp;&gt;&nbsp;2. Given that the lower <em>T<sub>C</sub></em> is, the higher the expected return is of playing <em>A</em>, we’ll just work on the simple case where <em>T<sub>C</sub></em>&nbsp;=&nbsp;<em>y</em>, realizing that this is an upper bound on the expected return of <em>A</em> given <em>T<sub>C</sub></em>&nbsp;≤&nbsp;y. The expected return of <em>A</em> is 4 times the probability that Column will play <em>a</em>, i.e., 4 times the probability that <em>s<sub>C</sub></em>&nbsp;&lt;&nbsp;<em>T<sub>C</sub></em>. Given all the symmetries that have been built into the puzzle, we know that the probability that <em>s<sub>C</sub></em>&nbsp;&lt;&nbsp;<em>s<sub>R</sub></em> is 0.5. So the expected return of playing <em>A</em> is at most 2 if <em>s<sub>R</sub></em> ≥ <em>y</em>. But the expected return of playing <em>B</em> is, as we showed in the last paragraph, <em>s<sub>R</sub></em>, which is greater than 2. So it is better to play <em>B</em> than <em>A</em> if <em>s<sub>R</sub></em>&nbsp;≥&nbsp;<em>y</em>. And the difference is substantial, so even if <em>s<sub>R</sub></em> is epsilon less than that <em>y</em>, it will still be better to play <em>B</em>. (This is rather hand-wavy, but I’ll go over the more rigorous version presently.)</p>
<p>So for any <em>y</em>&nbsp;&gt;&nbsp;2 if <em>T<sub>C</sub></em>&nbsp;≤&nbsp;<em>y</em> we can prove that <em>T<sub>R</sub></em> should be lower still, because given that assumption it is better to play <em>B</em> even if the signal is just less than <em>y</em>. Repeating this reasoning over and over again pushes us to it being better to play <em>B</em> than <em>A</em> as long as <em>s<sub>R</sub></em>&nbsp;&gt;&nbsp;2. The same kind of reasoning from the opposite end pushes us to it being better to play <em>A</em> than <em>B</em> as long as <em>s<sub>R</sub></em>&nbsp;&lt;&nbsp;2. So we get <em>s<sub>R</sub></em>&nbsp;=&nbsp;2 as the uniquely rational solution to the game.</p>
<!--
Let's make that a touch more rigorous. Assume that *T~C~* = y, and *s~R~* is slightly less than *y*. In particular, we'll assume that *z* = *y* - *s~R~* is in (0, 0.5). Then the probability that *s~C~* \< *y* is 0.5 + 2*z* ‑ 2*z*^2^. So the expected return of playing *A* is 2 + 8*z* ‑ 8*z*^2^. And the expected return of playing *B* is, again, *sR*. These will be equal iff *s~R~* = $\frac{\sqrt{145-32y}-9}{16}$. So if we know that *T~C~* ≥ *y*, we know that *T~R~* ≥ *y* + $\frac{\sqrt{145-32y}-9}{16}$, which will be less than *y* if *y* \> 2. Then by symmetry, we know that *T~C~* must be at most as large as that as well. Then we can use that fact to derive a further upper bound on *T~R~* and hence on *T~C~*, and so on. And this will continue until we push both down to 2. It does require quite a number of steps of iterated deletion. [Table @tbl-threshold] shows the upper bound on the threshold after *n* rounds of deletion of dominated strategies. (The numbers in @tbl-threshold are precise for the first two rounds, and correct to three significant figures after that.)
-->
<p>Let’s make that a touch more rigorous. Assume that <em>T<sub>C</sub></em>&nbsp;=&nbsp;y, and <em>s<sub>R</sub></em> is slightly less than <em>y</em>. In particular, we’ll assume that <em>z</em>&nbsp;=&nbsp;<em>y</em>&nbsp;-&nbsp;<em>s<sub>R</sub></em> is in (0, 0.5). Then the probability that <em>s<sub>C</sub></em>&nbsp;&lt;&nbsp;<em>y</em> is 0.5&nbsp;+&nbsp;2<em>z</em>&nbsp;‑&nbsp;2<em>z</em><sup>2</sup>. So the expected return of playing <em>A</em> is 2&nbsp;+&nbsp;8<em>z</em>&nbsp;‑&nbsp;8<em>z</em><sup>2</sup>. And the expected return of playing <em>B</em> is, again, <em>sR</em>. These will be equal iff <em>s<sub>R</sub></em>&nbsp;=&nbsp;<em>y</em>&nbsp;+&nbsp;((145&nbsp;-&nbsp;32<em>y</em>)<sup>½</sup>&nbsp;-&nbsp;9)/16. So if we know that <em>T<sub>C</sub></em>&nbsp;≥&nbsp;<em>y</em>, we know that <em>T<sub>R</sub></em>&nbsp;≥&nbsp;<em>y</em>&nbsp;+&nbsp;((145&nbsp;-&nbsp;32<em>y</em>)<sup>½</sup>&nbsp;-&nbsp;9)/16, which will be less than <em>y</em> if <em>y</em>&nbsp;&gt;&nbsp;2. Then by symmetry, we know that <em>T<sub>C</sub></em> must be at most as large as that as well. Then we can use that fact to derive a further upper bound on <em>T<sub>R</sub></em> and hence on <em>T<sub>C</sub></em>, and so on. And this will continue until we push both down to 2. It does require quite a number of steps of iterated deletion. <a href="#tbl-threshold" class="quarto-xref">Table&nbsp;<span>9.6</span></a> shows the upper bound on the threshold after <em>n</em> rounds of deletion of dominated strategies. (The numbers in <a href="#tbl-threshold" class="quarto-xref">Table&nbsp;<span>9.6</span></a> are precise for the first two rounds, and correct to three significant figures after that.)</p>
<div id="tbl-threshold" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-threshold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.6: How the threshold moves towards 2.
</figcaption>
<div aria-describedby="tbl-threshold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;"><em>Round</em></td>
<td style="text-align: center;"><em>Upper Bound on Threshold</em></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">4.250</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">3.875</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">3.599</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">3.378</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">3.195</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">3.041</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: center;">2.910</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2.798</td>
</tr>
<tr class="even">
<td style="text-align: center;">9</td>
<td style="text-align: center;">2.701</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">2.617</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>That is, <em>T<sub>R</sub></em>&nbsp;=&nbsp;4.25 dominates any strategy with a tipping point above 4.25. And <em>T<sub>R</sub></em>&nbsp;=&nbsp;3.875 dominates any strategy with a higher tipping point than 3.875, assuming <em>T<sub>C</sub></em>&nbsp;≤&nbsp;4.25. And <em>T<sub>R</sub></em>&nbsp;≈&nbsp;3.599 dominates any strategy with a higher tipping point than 3.599, assuming <em>T<sub>C</sub></em>&nbsp;≤&nbsp;3.875. And so on.</p>
<p>Similar reasoning shows that at each stage not only are all strategies with higher tipping points dominated, but so are strategies that assign positive probability (whether it is 1 or less than 1), to playing <em>A</em> when the signal is above the ‘tipping point’.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;If we’re careful about how we state this, we can use this to rule out all mixed strategies except those that respond probabilistically to <em>s<sub>R</sub></em>&nbsp;=&nbsp;2</p></div></div><p>So it has been shown that iterated deletion of dominated strategies will rule out all strategies except the risk-optimal equilibrium. The possibility that <em>x</em> is greater than the maximal return for <em>A</em> is needed to get the iterated dominance going. We also need the signal to have an error bar to it, so that each round of iteration removes more strategies. But that’s all that was needed; the particular values used are irrelevant to the proof.</p>
</section>
<section id="sec-perfectri" class="level3 page-columns page-full" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="sec-perfectri"><span class="header-section-number">9.4.2</span> Making One Signal Precise</h3>
<p>So far I’ve just been setting out Carlsson and van Damme’s results. It’s time to prove something just slightly stronger. I’ll show that the result in <a href="#sec-cvdproof" class="quarto-xref"><span>Section 9.4.1</span></a> did not require that both parties receive a noisy signal. It’s enough that just one party does.</p>
<p>More precisely, I’ll change the game so that it is common knowledge that the signal Column gets, <em>s<sub>C</sub></em>, equals <em>x</em>. Since the game is no longer symmetric, I can’t just appeal to the symmetry of the game as frequently as in the previous subsection. This slows the proof down, but doesn’t stop it.</p>
<p>This change actually helps us at the first stage of the argument. Since Column could not be wrong about <em>x</em>, Column knows that if <em>s<sub>C</sub></em>&nbsp;&gt;&nbsp;4 then playing <em>b</em> dominates playing <em>a</em>. So one round of deleting dominated strategies rules out <em>T<sub>C</sub></em>&nbsp;&gt;&nbsp;4, as well as ruling out <em>T<sub>R</sub></em>&nbsp;&gt;&nbsp;4.25.</p>
<p>At any stage for any <em>y</em>&nbsp;&gt;&nbsp;2 such that we know <em>T<sub>C</sub></em>&nbsp;≤&nbsp;y, the strategy <em>T<sub>R</sub></em>&nbsp;=&nbsp;<em>y</em> dominates <em>T<sub>R</sub></em>&nbsp;&gt;&nbsp;<em>y</em>. That’s because if <em>s<sub>R</sub></em>&nbsp;≥&nbsp;<em>y</em>, and <em>T<sub>C</sub></em>&nbsp;≤&nbsp;<em>y</em>, the probability that Column will play <em>a</em> (given Row’s signal) is less than 0.5. After all, the signal is just as likely to be above <em>x</em> as below it.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> So if <em>s<sub>R</sub></em> is at or above <em>T<sub>C</sub></em>, the probability that Column’s signal is above Column’s tipping point is at least 0.5. So the probability that Column will play <em>b</em> is at least 0.5. So the expected return to Row of playing <em>A</em>, which is 4 times the probability that Column will play <em>a</em>, is at most 2. Since the expected return to Row of playing <em>B</em> equals the value of the signal<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>, that means that if the signal is above 2, they should play <em>B</em>.</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;This isn’t strictly true if the signal is close enough to 5, but in that case we have an independent reason to think Column will play <em>a</em>.</p></div><div id="fn5"><p><sup>5</sup>&nbsp;Unless the signal is very close to 5, in which case they should play <em>B</em> anyway.</p></div></div><p>Summing up, if Row knows <em>T<sub>C</sub></em>&nbsp;≤&nbsp;<em>y</em>, for any <em>y</em>&nbsp;&gt;&nbsp;2, Row also knows it is better to play <em>B</em> if <em>s<sub>R</sub></em> ≥ <em>y</em>. That is, if Row knows <em>T<sub>C</sub></em>&nbsp;≤&nbsp;<em>y</em>, for any <em>y</em>&nbsp;&gt;&nbsp;2, Row’s tipping point should be at most <em>y</em>.</p>
<p>Assume now that it is common knowledge that <em>T<sub>R</sub></em>&nbsp;≤&nbsp;<em>y</em>, for some <em>y</em>&nbsp;&gt;&nbsp;2. Assume Column’s signal, which we’ll call <em>x</em>, is just a little less than <em>y</em>. In particular, define <em>z</em>&nbsp;=&nbsp;<em>y</em>&nbsp;-&nbsp;<em>x</em>, and assume <em>z</em>&nbsp;∈&nbsp;(0, 0.25). We want to work out the upper bound on the expected return to Column of playing <em>a</em>. (The return of playing <em>b</em> is known, it is <em>x</em>.)</p>
<p>The expected return to Column of playing <em>a</em> will be highest when <em>T<sub>R</sub></em> is highest. So we can work out an upper bound on that expected return by assuming that <em>T<sub>R</sub></em>&nbsp;=&nbsp;<em>y</em>. Given that assumption, the probability that Row plays <em>A</em> is (1&nbsp;+&nbsp;2<em>z</em>)/2. (That’s the probability that Row’s signal, which is a random draw from [<em>x</em>&nbsp;-&nbsp;¼,&nbsp;<em>x</em>&nbsp;+&nbsp;¼], is above <em>y</em>.) So the expected return of playing <em>a</em> is 2&nbsp;+&nbsp;4<em>z</em>, i.e., 2&nbsp;+&nbsp;4(<em>y</em>&nbsp;-&nbsp;<em>x</em>). That will be greater than <em>x</em> only when <em>x</em>&nbsp;&lt;&nbsp;(2&nbsp;+&nbsp;4<em>y</em>)/5.</p>
<p>So if it is common knowledge that <em>T<sub>R</sub></em>&nbsp;≤&nbsp;<em>y</em>, then it is best for Column to play <em>b</em> unless <em>x</em>&nbsp;&lt;&nbsp;(2&nbsp;+&nbsp;4<em>y</em>)/5. That is, if it is common knowledge that <em>T<sub>R</sub></em>&nbsp;≤&nbsp;<em>y</em>, then <em>T<sub>C</sub></em> must be at most (2&nbsp;+&nbsp;4<em>y</em>)/5.</p>
<p>The rest of the proof proceeds in a zig-zag fashion. At one stage, we show that <em>T<sub>R</sub></em> must be no greater than <em>T<sub>C</sub></em>. So whatever value we’ve shown to be an upper bound for <em>T<sub>C</sub></em> is also an upper bound for <em>T<sub>R</sub></em>. At the next stage, we show that given any upper bound on <em>T<sub>R</sub></em> greater than 2, we can derive a new upper bound on <em>T<sub>C</sub></em> which is lower still. This process will eventually rule out all values for <em>T<sub>R</sub></em> and <em>T<sub>C</sub></em> greater than 2. So just using iterated deletion of dominated strategies, we eventually rule out all strategies that are involve tipping points above 2.</p>
<p>There is one last point to be careful about. It takes infinitely many steps to rule out all tipping points above 2. Since it isn’t obviously sound to have infinitely many steps of iterated deletion, one might worry about the soundness of the proof at this point. The key thing to note is that for any tipping point above 2, it is ruled out in a finite number of steps. So purely finitary reasoning rules out all tipping points above 2. It’s just that there is no upper bound to the (finite!) number of steps needed.</p>
<p>This completes the mathematical part of the argument; I’ll return to discussing whether this result matters for thinking about evidence and rational action, and reply to some objections to thinking that it does.</p>
</section>
</section>
<section id="sec-evsolution" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-evsolution"><span class="header-section-number">9.5</span> Objections and Replies</h2>
<p><em>Objection</em>: The formal argument requires that in the ‘global game’ there are values for <em>x</em> that make <em>A</em> the dominant choice. These cases serve as a base step for an inductive argument that follows. But in Parveen’s case, there is no such setting for <em>x</em>, so the inductive argument can’t get going.</p>
<p><em>Reply</em>: What matters is that there are values of <em>x</em> such that <em>A</em> is the strictly dominant choice, and Human (or Parveen) doesn’t know that they know that they know, etc., that those values are not actual. And that’s true in our case. For all Human (or Parveen) knows that they know that they know that they know…, the proposition in question is not part of their evidence under a maximally expansive verdict on The Radical Interpreter’s part. So the relevant cases are there in the model, even if both players know that they know that they know … that the models don’t obtain, for a high but finite number of repetitions of ‘that they know’.</p>
<p><em>Objection</em>: This model is much more complex than the simple motivation for pragmatic encroachment.</p>
<p><em>Reply</em>: Sadly, this is true. I would like to have a simpler model, but I don’t know how to create one. I suspect any such simple model will just be incomplete; it won’t say what Parveen’s evidence is. In this respect, any simple model will look just like applying tools like Nash equilibria to coordination games. So more complexity will be needed, one way or another. I think paying this price in complexity is worth it overall, but I can see how some people might think otherwise.</p>
<p><em>Objection</em>: Change the case involving Human so that the bet loses 15 utils if <em>p</em> is false, rather than 100. Now the risk-dominant equilibrium is that Human takes the bet, and The Radical Interpreter says that <em>p</em> is part of Human’s evidence. But note that if it was clearly true that <em>p</em> was not part of Human’s evidence, then this would still be too risky a situation for them to know <em>p</em>. So whether it is possible that <em>p</em> is part of Human’s evidence, and not just part of their knowledge, matters.</p>
<p><em>Reply</em>: This is all true, and it shows that the view I’m putting forward is incompatible with some programs in epistemology. In particular, it is incompatible with E=K, since what it takes to be evidence on this story is slightly different from what it takes to be knowledge. The next section argues that this is independently plausible.</p>
</section>
<section id="sec-cutelim" class="level2 page-columns page-full" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="sec-cutelim"><span class="header-section-number">9.6</span> Evidence, Knowledge and Cut-Elimination</h2>
<p>In the previous section I noted that my theory of evidence is committed to denying Williamson’s E=K thesis. This is the thesis that says one’s evidence is all and only what one knows. What I say is consistent with, and arguably committed to, one half of that thesis. Nothing I’ve said here provides a reason to reject the implication that if <em>p</em> is part of one’s evidence, then one knows <em>p</em>. Indeed, the story I’m telling would have to be complicated even further if that fails. But I am committed to denying the other direction. On my view, there can be cases where someone knows <em>p</em>, but <em>p</em> is not part of their evidence.</p>
<p>My main reason for this comes from the kind of cases that Shyam Nair <span class="citation" data-cites="Nair2019">(<a href="references.html#ref-Nair2019" role="doc-biblioref">2019</a>)</span> describes as failures of ‘cut-elimination’. I’ll quickly set out what Nair calls cut-elimination, and why it fails, and then look at how it raises problems for E=K.</p>
<p>Start by assuming that we have an operator ⊨ such that Γ&nbsp;⊨&nbsp;<em>A</em> means that <em>A</em> can be rationally inferred from Γ. I’m following Nair (and many others) in using a symbol usually associated with logical entailment here, though this is potentially misleading. A big plotline in what follows will be that ⊨, so understood, behaves very differently from familiar notions of entailment.</p>
<p>For the purposes of this section, I’m staying somewhat neutral on what it means to be able to rationally infer <em>A</em> from Γ. In particular, I want everything that follows to be consistent with the interpretation that an inference is rational only if it produces knowledge. I don’t think that’s true; I think folks with misleading evidence can rationally form false beliefs, and I think the traveler in Dharmottara’s example rationally believes there is a fire. But there is a dialectical reason for staying neutral here. I’m arguing against one important part of the ‘knowledge first’ program, and I don’t want to do so by assuming the falsity of other parts of it. So for this section (only), I’ll write in a way that is consistent with saying rational belief requires knowledge.</p>
<p>Given that, one way to interpret Γ&nbsp;⊨&nbsp;<em>A</em> is that <em>A</em> can be known on the basis of Γ. What can be known on the basis of what is a function of, among other things, who is doing the knowing, what their background evidence is, what their capacities are, and so on. Strictly speaking, that suggests we should have some subscripts on ⊨ for who is the knower, what their background evidence is, and so on. In the interests of readability, I’m going to leave all those implicit. In the next section it will be important to come back and look at whether the force of some of these arguments is diminished if we are careful about this relativisation.</p>
<p>That’s our important notation. The principle <em>Cut</em> that Nair focuses on is that if 1 and 2 are true, so is 3.</p>
<ol type="1">
<li>Γ&nbsp;⊨&nbsp;A</li>
<li>{A}&nbsp;∪&nbsp;Δ&nbsp;⊨&nbsp;B</li>
<li>Γ&nbsp;∪&nbsp;Δ&nbsp;⊨&nbsp;B</li>
</ol>
<p>The principle is intuitive. Indeed, it is often implicit in a lot of reasoning. Here is one instance of it in action.</p>
<blockquote class="blockquote">
<p>I heard from a friend that Jack went up the hill. This friend is trustworthy, so I’m happy to infer that Jack did indeed go up the hill. I heard from another friend that Jack and Jill did the same thing. This friend is also trustworthy, so I’m happy to infer that Jill did the same thing as Jack, i.e., go up the hill.</p>
</blockquote>
<p>Normally we wouldn’t spell out the ‘happy to infer’ steps, but I’ve included them in here to make the reasoning a bit more explicit. But note what I didn’t need to make explicit, even in this laborious reconstruction. I didn’t need to note a change of status of the claim that Jack went up the hill. That goes from being a conclusion to being a premise. What matters for our purposes is that there doesn’t seem to be a gap between the rationality of inferring that Jack went up the hill, and the rationality of using that as a premise in later reasoning. The idea that there is no gap here just is the idea that the principle <em>Cut</em> is true.</p>
<p>Wwhile <em>Cut</em> seems intuitive in cases like this, Nair argues that it can’t be right in general. (If that’s right we have a duty, one Nair takes up, to explain why cases like Jack and Jill seem like cases of good reasoning.) For my purposes, it is helpful to divide the putative counterexamples to <em>Cut</em> into two categories. I’ll call them <em>monotonic</em> and <em>non-monotonic</em> counterexamples. The categorisation turns on whether Γ&nbsp;∪&nbsp;Δ&nbsp;⊨&nbsp;<em>A</em> is true assuming that Γ&nbsp;⊨&nbsp;A is true. I’ll call cases where it is true monotonic instances of <em>Cut</em>, and cases where it is false non-monotonic instances.</p>
<p>That <em>Cut</em> fails in non-monotonic cases is fairly obvious. We can see this with an example that was hackneyed a generation ago.</p>
<blockquote class="blockquote">
<p>Γ = {Tweety is a bird}<br>
Δ = {Tweety is a penguin}<br>
A = B = Tweety can fly</p>
<p>From Tweety is a bird we can rationally infer that Tweety flies. And given that Tweety is a flying penguin, we can infer that she flies. But given that Tweety is a penguin and a bird, we cannot infer this. So principles 1 and 2 in <em>Cut</em> are true, but 3 is false. And the same pattern will recur any time Δ provides a defeater for the link between Γ and <em>A</em>.</p>
</blockquote>
<p>These cases will matter in what follows, but they are rather different from the monotonic examples.The monotonic example I’ll set out (in the next three paragraphs) is very similar to one used in an argument against E=K by Alvin Goldman <span class="citation" data-cites="Goldman2009">(<a href="references.html#ref-Goldman2009" role="doc-biblioref">2009</a>)</span>. In many ways the argument against E=K I’m going to give is just a notational variant on Goldman’s, but I think the notation I’m borrowing from Nair helps bring out the argument’s strength.</p>
<p>Here is the crucial background assumption for the example. (I’ll come back to how plausible this is after setting the example up.) The nature of <em>F</em> around here varies, but it varies very very slowly. If we find a pattern in common to all the <em>F</em> within distance (in miles) <em>d</em> of here, we can rationally infer that the pattern extends another mile. That’s just boring induction. But we can’t infer that it extends to infinity, that would be a radical step. If we can’t infer that the pattern goes to infinity, there must be a point beyond which we can’t infer the pattern goes. Let’s say that’s one mile. So if we know the pattern holds within distance <em>d</em> of here, we can infer that it holds within distance <em>d</em>&nbsp;+&nbsp;1, but no more.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;In any remotely realistic case, it would make more sense to say we can infer it holds in some multiple of <em>d</em> rather than adding some value to <em>d</em>. But I’m simplifying a lot to make a point, and this is just one more simplification.</p></div></div><p>To see a case like this, imagine we’re doing work that’s more like working out the diet of local wildlife than working out the mass of an electron. If you know the mass of electrons around here, and what pigeons around here eat, there are some inferences you can make. You can come to know what the mass of electrons will be in the next town over, and what pigeons eat in the next town over. But there is a difference between the cases. You can also infer from this evidence what the mass of electrons will be on the other side of the world. But you can’t make very confident inferences about what pigeons eat on the other side of the world; they may have adapted their diet to local conditions. In our case <em>F</em> and <em>G</em> concern things more like pigeon diets than electron masses.</p>
<p>Now here is the counterexample.</p>
<blockquote class="blockquote">
<p>Γ = Δ = {Every <em>F</em> within 3 miles of here is <em>G</em>.}<br>
<em>A</em> = Every <em>F</em> between 3 and 4 miles of here is <em>G</em>.<br>
<em>B</em> = Every <em>F</em> between 4 and 5 miles of here is <em>G</em>.</p>
</blockquote>
<p>If what I said was right, then this is a counterexample to <em>Cut</em>. Γ&nbsp;⊨&nbsp;<em>A</em> is true because it says given evidence about all the <em>F</em> within 3 miles of here, we can infer that all the <em>F</em> within 4 miles are like them. And {<em>A</em>}&nbsp;∪&nbsp;Δ&nbsp;⊨&nbsp;<em>B</em> is true because because it says given evidence about all the <em>F</em> within 4 miles of here, we can infer that all the <em>F</em> within 5 miles are like them. But Γ&nbsp;∪&nbsp;Δ&nbsp;⊨&nbsp;<em>A</em> is false, because it purports to say that given evidence about the <em>F</em> within 3 miles of here, we can infer that all the <em>F</em> within 5 miles are alike. And that’s an inductive bridge too far.</p>
<p>This particular example involving distances was an extreme idealisation. But all we need for the larger argument is that there is some similarity metric such that inductive inference is rational across short jumps in that similarity metric, but not across long jumps. One kind of similarity is physical distance from a salient point. That’s not the only kind of similarity, and rarely the most important kind.</p>
<p>As long as there is some ‘inductive margin of inference’, the argument works. What I mean by an inductive margin of inference is that given that all the <em>F</em> that differ from a salient point (along this metric) by amount <em>d</em> are <em>G</em>, it is rational to infer that all the <em>F</em> that differ from that salient point by amount <em>d</em>&nbsp;+&nbsp;<em>m</em> are <em>G</em>, but not that all the <em>F</em> that differ from that salient point by amount <em>d</em>&nbsp;+&nbsp;2<em>m</em> are <em>G</em>. And it seems very plausible to me that there are some metrics, and values of <em>F</em>, <em>G</em>, <em>d</em>, <em>m</em> such that that’s true.</p>
<p>For example, given what I know about Miami’s weather, I can infer that it won’t snow there for the next few hundred Christmases. Indeed, I know that. But I can’t know that it won’t snow there for the next few million Christmases. There is some point, and I don’t know what it is, where my inductive knowledge about Miami’s snowfall (or lack thereof) gives out.</p>
<p>While it is plausible that such cases are possible, any particular case fitting this pattern is weird. Here’s what is weird about them. It will be easier to go back to the case where the metric is physical distance to set this out, but the weirdness will extend to all cases. Imagine we investigate the area within 3 miles of here thoroughly, and find that all the <em>F</em> are <em>G</em>s. We infer, and now know, that all the <em>F</em> within 4 miles of here are <em>G</em>s. We keep investigating, and keep observing, and after a while we’ve observed all the <em>F</em> within 4 miles. And they are all <em>G</em>, as we knew they would be. But now we are in a position to infer that all the <em>F</em> within 5 miles are <em>G</em>. Observing something that we knew to be true gives us a reason to do something, i.e., make a further inference, that we couldn’t do before. That’s weird, and I’m going to come back in the next section to how it relates to the story I told about knowledge in <a href="knowledge.html" class="quarto-xref"><span>Chapter 4</span></a>.</p>
<p>The key point now is that this possibility undermines E=K. There is a difference between knowing <em>A</em> and being able to use <em>A</em> to support further inductive inferences. It is very natural to call that the difference between knowing <em>A</em> and having <em>A</em> as evidence.</p>
<p>The reasoning that I’ve been criticising violates a principle Jonathan Weisberg calls <em>No Feedback</em> <span class="citation" data-cites="Weisberg2010">(<a href="references.html#ref-Weisberg2010" role="doc-biblioref">Weisberg, 2010: 533–4</a>)</span>. This principle says that if a conclusion is derived from some premises, plus some intermediary conclusions, then it is only justified if it could, at least in principle, be derived from those premises alone. A natural way to read this is that we have some evidence, and things that we know on the basis of that evidence have a different functional role from the evidence. They can’t do what the evidence itself can do, even if known. This looks like a problem for E=K, as Weisberg himself notes <span class="citation" data-cites="Weisberg2010">(<a href="references.html#ref-Weisberg2010" role="doc-biblioref">2010: 536</a>)</span>.</p>
<p>If any monotonic instances of failures of Cut exist, we need to distinguish between things the thinker knows by inference, and things they know by observation, in order to assess their inferences. That’s to say, some knowledge will not play the characteristic role of evidence. T suggests that E=K is false.</p>
</section>
<section id="sec-basic" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="sec-basic"><span class="header-section-number">9.7</span> Basic Knowledge and Non-Inferential Knowledge</h2>
<p>It would be natural to conclude from the examples I’ve discussed that evidence is something like non-inferential knowledge. This is very similar to a view defended by Patrick Maher <span class="citation" data-cites="Maher1996">(<a href="references.html#ref-Maher1996" role="doc-biblioref">1996</a>)</span>. And it is, I will argue, close to the right view. But it can’t be exactly right, for reasons Alexander Bird <span class="citation" data-cites="Bird2004">(<a href="references.html#ref-Bird2004" role="doc-biblioref">2004</a>)</span> brings out.</p>
<p>I will argue that evidence is not non-inferential knowledge, but rather basic knowledge. The primary difference between these two notions is that <em>being non-inferential</em> is a diachronic notion, it depends on the causal source of the knowledge, while being basic is a synchronic notion, it depends on how the knowledge is currently supported. In general, non-inferential knowledge will be basic knowledge, and basic knowledge will be non-inferential. But the two notions can come apart, and when they do, the evidence is what is basic, not what is non-inferential.</p>
<p>The following kind of case is central to Bird’s objection to the idea that evidence is non-inferential knowledge. Assume that our inquirer sees that <em>A</em> and rationally infers <em>B</em>. On the view that evidence is non-inferential knowledge, <em>A</em> is evidence but <em>B</em> is not. Now imagine that at some much later time, the inquirer remembers <em>B</em>, but has forgotten that it is based on <em>A</em>. This isn’t necessarily irrational. As Harman <span class="citation" data-cites="Harman1986">(<a href="references.html#ref-Harman1986" role="doc-biblioref">1986</a>)</span> stresses, an obligation to remember our evidence is wildly unrealistic. The inquirer learns <em>C</em> and infers <em>B</em>&nbsp;∧ <em>C</em>. This seems perfectly rational. But why is it rational?</p>
<p>If evidence is non-inferential knowledge, then this is a mystery. Since <em>B</em> was inferred, that can’t be the evidence that justifies <em>B</em>&nbsp;∧&nbsp;<em>C</em>. So the only other option is that the evidence is the, now forgotten, <em>A</em>. It is puzzling how something that is forgotten can now justify. But a bigger problem is that if <em>A</em> is the inquirer’s evidence, then they should also be able to infer <em>A</em>&nbsp;∧&nbsp;<em>C</em>. But this would be an irrational inference.</p>
<p>So I agree with Bird that we can’t identify evidence with non-inferential knowledge, if by that we mean knowledge that was not originally gained through inference. (And what else could it mean?) But a very similar theory of evidence can work. The thing about evidence is that it can play a distinctive role in reasoning, it provides a distinctive kind of reason. In particular, it provides basic reasons.</p>
<p>Evidence stops regresses. That’s why we can say that our fundamental starting points are self-evident. Now there is obviously a controversy about what things are self-evident. I don’t find it particularly likely that claims about the moral rights we were endowed with by our Creator are self-evident. But I do think it is true that a lot of things are self-evident. (Even including, perhaps, that we have moral rights.) We should take this notion of self-evidence seriously. Our evidence is that knowledge which provides basic reasons.</p>
<p>What is it for a reason to be basic? It isn’t that it was not originally inferred. Something that was once inferred from long forgotten premises may now be a basic reason. Rather, it is something that needs no further reason given as support. (Its support is itself, since it is self-evident.) What makes a reason need further support? I’m an interest-relative epistemologist, so I think this will be sensitive to the agent’s interests. For example, I think facts reported in a reliable history book are pieces of basic evidence when we are thinking about history, but not when we are thinking about the reliability of that book. But this kind of interest-relativity is inessential to the story. What is essential is that evidence provides a reason that does not in turn require more justification.</p>
<p>This picture suggests an odd result about cases of forgotten evidence. There is a much discussed puzzle about forgotten evidence that was set in motion by Gilbert Harman <span class="citation" data-cites="Harman1986">(<a href="references.html#ref-Harman1986" role="doc-biblioref">1986</a>)</span>. He argued that if someone irrationally believes <em>p</em> in the basis of some evidence, then later forgets the evidence but retains the belief, the belief may now be rational. It would not be rational if they remembered both the evidence, and that it was the evidence for <em>p</em>. But, and this is what I want to take away from the case, there is no obligation on thinkers to keep track of why they believe each of the things they do.</p>
<p>There is a large literature now on this case; Sinan Dogramaci <span class="citation" data-cites="Dogramaci2015">(<a href="references.html#ref-Dogramaci2015" role="doc-biblioref">2015</a>)</span> both provides a useful guide to the debate and moves it forward by considering what we might aim to achieve by offering one or other evaluation of the believer in this case. The view I’m offering here is, as far as I can tell, completely neutral on Harman’s original case. But it has something striking to say about a similar case.</p>
<p>Imagine an inquirer, call him Jaidyn, believes <em>p</em> for the excellent reason that he read it in a book from a reliable historian <em>H</em>. Six months later, he has forgotten that that’s where he learned that <em>p</em>, though he still believes that <em>p</em>. In a discussion about historians, a friend of Jaidyn’s says that <em>H</em> is really unreliable. Jaidyn is a bit shocked, and literally can’t believe it. This is for the best since <em>H</em> is in fact reliable, and his friend is suffering from a case of mistaken identity. But he is moved enough by the testimony to suspend judgment on <em>H</em>’s reliability, and so he forms a disposition to not believe anything <em>H</em> says without corroboration. Since he doesn’t know that he believes <em>p</em> because <em>H</em> says so, he doesn’t do anything about this belief. What should we say about Jaidyn’s belief that <em>p</em>?</p>
<p>Here’s what I want to say. I don’t claim this is particularly intuitive, but I’m not sure there is anything particularly intuitive; it’s best to just see what a theory says about the case. My theory says that Jaidyn still knows that <em>p</em>. This knowledge was once based on <em>H</em>’s testimony, but it is no longer based on that. Indeed, it is no longer based on anything. Presumably, if Jaidyn is rational, the knowledge will be sensitive to the absence of counter-evidence, or to incoherence with the rest of his world-view. But these are checks and balances in Jaidyn’s doxastic system, they aren’t the basis of the belief. Since the belief is knowledge, and is a basic reason for Jaidyn, it is part of his evidence.</p>
<p>Note three things about that last conclusion. First, this is a case where a piece of inferential knowledge can be in someone’s evidence. By (reasonably) forgetting the source of the knowledge, it converts to being evidence. Second, almost any knowledge could make this jump. Whenever someone has no obligation to remember the source or basis of some knowledge, they can reasonably forget the source, and the basis, and the knowledge will become basic. And then it is evidence. The picture I’m working with is that pieces of knowledge can easily move in and out of one’s evidence set; sometimes all it takes is forgetting where the knowledge came from. But third, if Jaidyn had done better epistemically, and remembered the source, he would no longer know that <em>p</em>.</p>
<p>It is somewhat surprising that knowledge can be dependent on forgetting. Jaidyn knows that <em>p</em>, but if he’d done better at remembering why he believes <em>p</em>, he wouldn’t know it. Still, the knowledge isn’t grounded in forgetting. It’s originally grounded in testimony from an actually reliable source, and Jaidyn did as good a job as he needed to in checking the reliability of the source before accepting the testimony. Now since Jaidyn is finite, he doesn’t have any obligation to remember everything. It seems odd to demand that Jaidyn adjust his beliefs on the basis of where they are from if he isn’t even required to track where they are from. It would be very odd to say that Jaidyn’s evidence now includes neither <em>p</em> (because it is undermined by his friend’s testimony), nor the fact that someone said that <em>p</em>. That suggests any <em>p</em>-related inferences Jaidyn makes are totally unsupported by his evidence, which doesn’t seem right.</p>
<p>So the picture of evidence as basic knowledge, combined with a plausible theory of when forgetting is permissible, suggests that the forgetful reader knows more than the reader with a better memory. I suspect the same thing will happen in versions of Goldman’s explosive inductive argument. Imagine a thinker observes all the <em>F</em>s within 3 miles, sees they are all <em>G</em>, and rationally infers that all the <em>F</em>s within 4 miles are <em>G</em>. Some time later they retain the belief, the knowledge actually, that all <em>F</em>s within 4 miles are <em>G</em>. But they forget that this was partially inferential knowledge, like Jaidyn forgot the source of his knowledge that <em>p</em>. They then make the seemingly sensible inductive inference that all <em>F</em>s within 5 miles are <em>G</em>. Is this rational, and can it produce knowledge? I think the answer is yes; if they (not unreasonably) forget the source of their knowledge that the <em>F</em>s 3 to 4 miles away are <em>G</em>, then this knowledge becomes basic. If it’s basic, it is evidence. And if it is evidence, it can support one round of inductive reasoning.</p>
<p>I’ve drifted a fair way from discussing interest-relativity. And a lot of what I say here is inessential to defending IRT. So I’ll return to the main plotline with a discussion of how my view of evidence helps respond to a challenge Ram Neta issues to IRT, and implies a rejection of a key principle in Jeremy Fantl and Matthew McGrath’s theory of knowledge.</p>
</section>
<section id="sec-neta" class="level2 page-columns page-full" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="sec-neta"><span class="header-section-number">9.8</span> Holism and Defeaters</h2>
<p>The picture of evidence I’ve outlined here grounds a natural response to a nice puzzle case due to Ram Neta <span class="citation" data-cites="Neta2007">(<a href="references.html#ref-Neta2007" role="doc-biblioref">2007</a>)</span>.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;This section draws my <span class="citation" data-cites="Weatherson2011-WEADIR">(<a href="references.html#ref-Weatherson2011-WEADIR" role="doc-biblioref">2011</a> §5)</span>.</p></div></div><blockquote class="blockquote">
<p>Kate needs to get to Main Street by noon: her life depends upon it. She is desperately searching for Main Street when she comes to an intersection and looks up at the perpendicular street signs at that intersection. One street sign says “State Street” and the perpendicular street sign says “Main Street.” Now, it is a matter of complete indifference to Kate whether she is on State Street–nothing whatsoever depends upon it. <span class="citation" data-cites="Neta2007">(<a href="references.html#ref-Neta2007" role="doc-biblioref">Neta, 2007: 182</a>)</span></p>
</blockquote>
<p>Neta argues that IRT implies Kate knows that she is on State Street, but does not know that she is on Main Street. He suggests this is intuitively implausible. I think I agree with that intuition, so let’s take it for granted and ask whether IRT has this problematic implication.</p>
<p>Let’s also assume that it is not rational for Kate to take the street sign’s word for it. I’m not sure that’s true actually, but let’s assume it to get the argument going. I think Neta is reasoning that since Kate’s life depends on it, then IRT must say that she can’t trust street signs, because the stakes are so high.</p>
<p>That claim about the relation between stakes and what one can take for granted can’t be right. I often take actions that my life depends on going by the say so of signs. For example, I often turn onto the freeway ramp labelled on ramp, and not the ramp labelled off ramp, without really double checking. If I was wrong about this there is a very high chance I’d be very quickly killed. (Wrong-way crashes on freeways are a very common kind of fatal collisions.) If Kate can’t take the sign for granted, it isn’t just because her life is at stake; somewhat disconcertingly, that doesn’t make the case any different from everyday driving.</p>
<p>But maybe Kate has some other way of checking where she is - like a map on a phone in her pocket - and it would be irrational to take the sign for granted and not check that other map. So I’m not going to push on this assumption.</p>
<p>So what evidence should The Radical Interpreter assign to Kate? It doesn’t seem to be at issue that Kate sees that the signs say State and Main. The big question is whether she can simply take it as evidence that she is on State and Main. That is, do the contents of the sign simply become part of Kate’s evidence? (Assume that the signs are accurate and there is no funny business going on, so it is plausible that the signs contribute this evidence.) There are three natural options.</p>
<ol type="1">
<li>Both signs supply evidence directly to Kate, so her evidence includes that she is on State and that she is on Main.</li>
<li>Neither sign contributes evidence directly to Kate, so her evidence includes what the signs say, but nothing directly about her location.</li>
<li>One sign contributes evidence directly to Kate, but the other does not.</li>
</ol>
<p>Option 1 implies that Kate is rational to not check further whether she is on Main Street. And that’s irrational, so option 1 is out.</p>
<p>Option 3 implies that the signs behave differently, and that The Rational Interpreter will assign them different roles in Kate’s cognitive architecture. But this will be true even though the signs are equally reliable, and Kate’s evidence about their reliability is identical. So Kate treating them differently would be irrational, and The Radical Interpreter does not want to make Kate irrational if it can be helped. So option 3 is out.</p>
<p>That leaves Option 2. Kate’s evidence does not include that she is on State, and does not include that she is on Main. The latter ‘non-inclusion’ is directly explained by pragmatic factors. The former is explained by those factors plus the requirement that Kate’s evidence is what The Radical Interpreter says it is, and The Radical Interpreter’s desire to make Kate rational.</p>
<p>So Kate’s evidence doesn’t distinguish between the streets. It does, however, include that the signs say she is on State and that she is on Main. Could she be entitled in inferring that she is on State, but not that she is on Main?</p>
<p>It is hard to see how this could be so. Street signs are hardly basic epistemic sources. They are the kind of evidence we should be ‘conservative’ about in the sense of <span class="citation" data-cites="Pryor2004">Pryor (<a href="references.html#ref-Pryor2004" role="doc-biblioref">2004</a>)</span>. We should only use them if we antecedently believe they are correct. So for Kate to believe she’s on State, she’d have to believe the street signs she can see are correct. If not, she’d incoherently be relying on a source she doesn’t trust, even though it is not a basic source. But if she believes the street signs are correct, she’d believe she was on Main, and that would lead to practical irrationality. So there’s no way to coherently add the belief that she’s on State Street to her stock of beliefs. So she doesn’t know, and can’t know, that she’s either on State or on Main. This is, in a roundabout way, due to the practical situation Kate faces.</p>
<p>Neta thinks that the best way for IRT to handle this case is to say that the high stakes associated with the proposition that Kate is on Main Street imply that certain methods of belief formation do not produce knowledge. And he argues, plausibly, that such a restriction will lead to implausibly sceptical results.</p>
<p>What to say about this suggestion turns on how we understand what a ‘method’ is. If methods are individuated very finely, like <em>Trust street signs right here</em>, then it’s plausible that Kate should restrict what methods she uses, but implausible that this is badly sceptical. If methods are individuated very coarsely, like <em>Trust written testimony</em>, then it’s plausible that this is badly sceptical, but implausible that Kate should give up on methods this general. I can rationally treat some parts of a book as providing direct evidence about the world, and other, more speculative, parts as providing direct evidence about what the author says, and hence indirect evidence about the world. Similarly, Kate can treat these street signs as indirect evidence about her location, while still treating other signs around her as providing direct evidence. So there is no sceptical threat here.</p>
<p>But while the case doesn’t show IRT is false, it does tell us something interesting about the implications of IRT. When a practical consideration defeats a claim to know that <em>p</em>, it will often also knock out nearby knowledge claims. Some of these are obvious, like that the practical consideration defeats the claim to know 0=0 → <em>p</em>. But some of these are more indirect. When the inquirer knows what her evidence is, and knows that she has just the same evidence for <em>q</em> as for <em>p</em>, then if a practical consideration defeats a claim to know <em>p</em>, it also defeats a claim to know <em>q</em>. In practice, this makes IRT a somewhat more sceptical theory than it may have first appeared. It’s not so sceptical as to be implausible, but it’s more sceptical than is immediately obvious. This kind of result, where IRT ends up being somewhat sceptical but not implausibly so, has been a theme of many different cases throughout the book.</p>
</section>
<section id="sec-weakness" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="sec-weakness"><span class="header-section-number">9.9</span> Epistemic Weakness</h2>
<p>The cases where cut-elimination fails raise a problem for the way that Jeremy Fantl and Matthew McGrath spell out their version of IRT. Here is a principle they rely on in motivating IRT.</p>
<blockquote class="blockquote">
<p>When you know a proposition <em>p</em>, no weaknesses in your epistemic position with respect to <em>p</em>—no weaknesses, that is, in your standing on any truth-relevant dimension with respect to <em>p</em>—stand in the way of <em>p</em> justifying you in having further beliefs. <span class="citation" data-cites="FantlMcGrath2009">(<a href="references.html#ref-FantlMcGrath2009" role="doc-biblioref">Fantl &amp; McGrath, 2009: 64</a>)</span></p>
</blockquote>
<p>And a few pages later they offer the following gloss on this principle.</p>
<blockquote class="blockquote">
<p>We offer no analysis of the intuitive notion of ‘standing in the way’. But we do think that, when Y does not obtain, the following counterfactual condition is sufficient for a subject’s position on some dimension d to be something that stands in the way of Y obtaining: whether Y obtains can vary with variations in the subject’s position on d, holding fixed all other factors relevant to whether Y obtains. <span class="citation" data-cites="FantlMcGrath2009">(<a href="references.html#ref-FantlMcGrath2009" role="doc-biblioref">Fantl &amp; McGrath, 2009: 67</a>)</span></p>
</blockquote>
<p>This gloss suggests that the difference between knowledge and evidence is something that stands in the way of an inference. The inquirer who knows that nearby <em>F</em>s are <em>G</em>s, but does not know that somewhat distant <em>F</em>s are <em>G</em>s, has many things standing in the way of this knowledge. One of them is, according to this test, that her evidence does not include that all nearby <em>F</em>s are <em>G</em>s. Yet this is something she knows. So a weakness in her epistemic position with respect to the nature of nearby <em>F</em>s, that it is merely evidence and not knowledge, stands in the way of it justifying further beliefs.</p>
<p>The same thing will be true in the monontonic cases of cut-elimination failure. The thinker whose evidence includes Γ ∪ Δ, and whose inferential knowledge includes <em>A</em>, cannot infer <em>B</em>. But if they had <em>A</em> as evidence, and not merely as knowledge, then they could infer <em>B</em>. So the weakness in their epistemic position, the gap between evidence and knowledge, stands in the way of something.</p>
<p>I didn’t endorse the principle of Fantl and McGrath’s quoted above, but I did endorse very similar principles, and one might wonder whether they are subject to the same criticism. The main principle I endorsed was that if one knows that <em>p</em>, one is immune from criticism for using <em>p</em> on the grounds that <em>p</em> might be false, or is too risky to use. Equivalently, if the use of <em>p</em> in an inference is defective, but <em>p</em> is known, the explanation of why it is defective cannot be that <em>p</em> is too risky. But now won’t the same problem arise? Our inquirer in the monotonic cut-elimination example can’t use <em>A</em> in reasoning to <em>B</em>. If <em>A</em> was part of their evidence, then it wouldn’t be risky, and they would be able to use it. So the risk is part of what makes the use of it mistaken.</p>
<p>I reject the very last step in that criticism. The fact that something is wrong, and that it wouldn’t have been wrong if X, does not mean the non-obtaining of X is part of the ground, or explanation, for why it is wrong. If I break a law, then what I do is illegal. Had the law in question been struck down by a constitutional court, then my action wouldn’t have been illegal. Similarly, if the law had been repealed, my action would not have been illegal. But that doesn’t imply that the ground or explanation of the illegality of my action is the court’s not striking the law down, or the later legislature not repealing the law. That is to put too much into the notion of ground or explanation. No, what makes the act illegal is that a particular piece of legislation was passed, and this act violates it. This explanation is defeasible - it would be defeated if a court or later legislature had stepped in - but it is nonetheless complete.</p>
<p>The same thing is true in the case of knowledge and evidence. Imagine an inquirer who observes all the <em>F</em>s within 3 miles being <em>G</em>, and infers both that all the <em>F</em>s within 4 miles are <em>G</em>, and, therefore, that all the <em>F</em>s within 5 miles are <em>G</em>. The intermediate step is, in a sense, risky. And the final step is bad. And the final step wouldn’t have been bad if the intermediate step hadn’t been risky. But it’s not the riskiness that makes the second inference bad. No, what makes the second inference bad is that it violates Weisberg’s No Feedback principle. That’s what the reasoner can be criticised for, not for taking an epistemic risk.</p>
<p>There are two differences then between the core principle I rely on - using reasons that are known provides immunity to criticism for taking epistemic risks - and the principle Fantl and McGrath rely on. I use a concept of epistemic risk where they use a concept of strength of epistemic position. I don’t think these are quite the same thing, but they are clearly similar. But the bigger difference is that they endorse a counterfactual gloss of their principle, and I reject any such counterfactual gloss. I don’t say that the person who uses known <em>p</em> is immune to all criticisms that would have been vitiated had <em>p</em> been less risky. I just say that the risk can’t be the ground of the criticism; something else must be. In some cases, including this one, that ‘something else’ might be correlated with risk. But it must be the explanation.</p>
<p>Of course, this difference between my version of IRT and Fantl and McGrath’s is tiny compared to how much our theories have in common. And indeed, it’s tiny compared to how much my theory simply borrows from theirs. But it’s helpful I think to highlight the differences to understand the choice points within versions of IRT.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Bird2004" class="csl-entry" role="listitem">
Bird, Alexander. (2004). Is evidence non-inferential? <em>Philosophical Quarterly</em>, <em>54</em>(215), 252–265. doi:<a href="https://doi.org/10.1111/j.0031-8094.2004.00350.x">10.1111/j.0031-8094.2004.00350.x</a>
</div>
<div id="ref-CarlssonVanDamme1993" class="csl-entry" role="listitem">
Carlsson, Hans, and Eric van Damme. (1993). Global games and equilibrium selection. <em>Econometrica</em>, <em>61</em>(5), 989–1018. doi:<a href="https://doi.org/10.2307/2951491">10.2307/2951491</a>
</div>
<div id="ref-Dogramaci2015" class="csl-entry" role="listitem">
Dogramaci, Sinan. (2015). Forget and forgive: A practical approach to forgotten evidence. <em>Ergo</em>, <em>2</em>(26), 645–677. doi:<a href="https://doi.org/10.3998/ergo.12405314.0002.026">10.3998/ergo.12405314.0002.026</a>
</div>
<div id="ref-FantlMcGrath2009" class="csl-entry" role="listitem">
Fantl, Jeremy, and Matthew McGrath. (2009). <em>Knowledge in an uncertain world</em>. Oxford University Press.
</div>
<div id="ref-Goldman2009" class="csl-entry" role="listitem">
Goldman, Alvin. (2009). Williamson on knowledge and evidence. In Patrick Greenough &amp; Duncan Pritchard (Eds.), <em><span class="nocase">Williamson on Knowledge</span></em> (73–91). Oxford University Press.
</div>
<div id="ref-Harman1986" class="csl-entry" role="listitem">
Harman, Gilbert. (1986). <em>Change in view</em>. <span>MIT</span> Press.
</div>
<div id="ref-Harper1986" class="csl-entry" role="listitem">
Harper, William. (1986). Mixed strategies and ratifiability in causal decision theory. <em>Erkenntnis</em>, <em>24</em>(1), 25–36. doi:<a href="https://doi.org/10.1007/BF00183199">10.1007/BF00183199</a>
</div>
<div id="ref-Humberstone2016" class="csl-entry" role="listitem">
Humberstone, Lloyd. (2016). <em>Philsophical applications of modal logic</em>. College Publications.
</div>
<div id="ref-Maher1996" class="csl-entry" role="listitem">
Maher, Patrick. (1996). Subjective and objective confirmation. <em>Philosophy of Science</em>, <em>63</em>(2), 149–174. doi:<a href="https://doi.org/10.1086/289906">10.1086/289906</a>
</div>
<div id="ref-Nair2019" class="csl-entry" role="listitem">
Nair, Shyam. (2019). Must good reasoning satisfy cumulative transitivity? <em>Philosophy and Phenomenological Research</em>, <em>98</em>(1), 123–146. doi:<a href="https://doi.org/10.1111/phpr.12431">10.1111/phpr.12431</a>
</div>
<div id="ref-Neta2007" class="csl-entry" role="listitem">
Neta, Ram. (2007). Anti-intellectualism and the knowledge-action principle. <em>Philosophy and Phenomenological Research</em>, <em>75</em>(1), 180–187. doi:<a href="https://doi.org/10.1111/j.1933-1592.2007.00069.x">10.1111/j.1933-1592.2007.00069.x</a>
</div>
<div id="ref-Pryor2004" class="csl-entry" role="listitem">
Pryor, James. (2004). What’s wrong with moore’s argument? <em>Philosophical Issues</em>, <em>14</em>(1), 349–378. doi:<a href="https://doi.org/10.1111/j.1533-6077.2004.00034.x">10.1111/j.1533-6077.2004.00034.x</a>
</div>
<div id="ref-Rousseau1913" class="csl-entry" role="listitem">
Rousseau, Jean-Jacques. (1913). <em>Social contract &amp; discourses</em> (G. D. H. Cole, Trans.). J. M. Dent &amp; Sons.
</div>
<div id="ref-Skyrms2001" class="csl-entry" role="listitem">
Skyrms, Brian. (2001). The stag hunt. <em>Proceedings and Addresses of the American Philosophical Association</em>, <em>75</em>(2), 31–41. doi:<a href="https://doi.org/10.2307/3218711">10.2307/3218711</a>
</div>
<div id="ref-Weatherson2011-WEADIR" class="csl-entry" role="listitem">
Weatherson, Brian. (2011). Defending interest-relative invariantism. <em>Logos &amp; Episteme</em>, <em>2</em>(4), 591–609. doi:<a href="https://doi.org/10.5840/logos-episteme2011248">10.5840/logos-episteme2011248</a>
</div>
<div id="ref-Weatherson2018-WEAIEA-2" class="csl-entry" role="listitem">
Weatherson, Brian. (2018). Interests, evidence and games. <em>Episteme</em>, <em>15</em>(3), 329–344.
</div>
<div id="ref-Weisberg2010" class="csl-entry" role="listitem">
Weisberg, Jonathan. (2010). Bootstrapping in general. <em>Philosophy and Phenomenological Research</em>, <em>81</em>(3), 525–548. doi:<a href="https://doi.org/10.1111/j.1933-1592.2010.00448.x">10.1111/j.1933-1592.2010.00448.x</a>
</div>
<div id="ref-Williamson2000" class="csl-entry" role="listitem">
Williamson, Timothy. (2000). <em><span class="nocase">Knowledge and its Limits</span></em>. Oxford University Press.
</div>
</div>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./rationality.html" class="pagination-link" aria-label="Rationality">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Rationality</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./power.html" class="pagination-link" aria-label="Power">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Power</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/bweatherson/kahis-quarto/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>